# Generated by Django 5.2.5 on 2025-08-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=64)),
                ('consent_personal_data', models.BooleanField(default=False)),
                ('utm_source', models.CharField(blank=True, default='', max_length=64)),
                ('utm_medium', models.CharField(blank=True, default='', max_length=64)),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=128)),
                ('utm_term', models.CharField(blank=True, default='', max_length=128)),
                ('utm_content', models.CharField(blank=True, default='', max_length=128)),
                ('referer', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
