# Generated by Django 5.2.5 on 2025-08-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='telegram',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
