# Generated by Django 5.2.5 on 2025-08-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmoAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(blank=True, default='')),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('token_type', models.CharField(blank=True, default='Bearer', max_length=32)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('base_domain', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
